// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
    id,
    customer_id,
    vehicle_id,
    dealership_id,
    technician_id,
    service_bay_id,
    service_type_id,
    start_time_utc,
    end_time_utc,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    'confirmed'
)
RETURNING id, customer_id, vehicle_id, dealership_id, technician_id, service_bay_id, service_type_id, start_time_utc, end_time_utc, status, created_at_utc
`

type CreateAppointmentParams struct {
	ID            pgtype.UUID        `json:"id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	VehicleID     pgtype.UUID        `json:"vehicle_id"`
	DealershipID  pgtype.UUID        `json:"dealership_id"`
	TechnicianID  pgtype.UUID        `json:"technician_id"`
	ServiceBayID  pgtype.UUID        `json:"service_bay_id"`
	ServiceTypeID pgtype.UUID        `json:"service_type_id"`
	StartTimeUtc  pgtype.Timestamptz `json:"start_time_utc"`
	EndTimeUtc    pgtype.Timestamptz `json:"end_time_utc"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ID,
		arg.CustomerID,
		arg.VehicleID,
		arg.DealershipID,
		arg.TechnicianID,
		arg.ServiceBayID,
		arg.ServiceTypeID,
		arg.StartTimeUtc,
		arg.EndTimeUtc,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VehicleID,
		&i.DealershipID,
		&i.TechnicianID,
		&i.ServiceBayID,
		&i.ServiceTypeID,
		&i.StartTimeUtc,
		&i.EndTimeUtc,
		&i.Status,
		&i.CreatedAtUtc,
	)
	return i, err
}

const findAvailableServiceBays = `-- name: FindAvailableServiceBays :many
SELECT sb.id, sb.dealership_id, sb.name, sb.created_at_utc
FROM service_bays AS sb
JOIN service_bay_capabilities AS sbc
  ON sbc.service_bay_id = sb.id
 AND sbc.service_type_id = $1
WHERE sb.dealership_id = $2
  AND NOT EXISTS (
      SELECT 1
      FROM appointments AS a
      WHERE a.service_bay_id = sb.id
        AND a.status = 'confirmed'
        AND a.start_time_utc < $3
        AND a.end_time_utc > $4
  )
ORDER BY sb.id
`

type FindAvailableServiceBaysParams struct {
	ServiceTypeID  pgtype.UUID        `json:"service_type_id"`
	DealershipID   pgtype.UUID        `json:"dealership_id"`
	RequestedEnd   pgtype.Timestamptz `json:"requested_end"`
	RequestedStart pgtype.Timestamptz `json:"requested_start"`
}

func (q *Queries) FindAvailableServiceBays(ctx context.Context, arg FindAvailableServiceBaysParams) ([]ServiceBay, error) {
	rows, err := q.db.Query(ctx, findAvailableServiceBays,
		arg.ServiceTypeID,
		arg.DealershipID,
		arg.RequestedEnd,
		arg.RequestedStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceBay{}
	for rows.Next() {
		var i ServiceBay
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.Name,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAvailableTechnicians = `-- name: FindAvailableTechnicians :many
SELECT t.id, t.dealership_id, t.name, t.created_at_utc
FROM technicians AS t
JOIN service_types AS st
  ON st.id = $1
JOIN technician_skills AS ts
  ON ts.technician_id = t.id
 AND ts.skill = st.required_skill
WHERE t.dealership_id = $2
  AND NOT EXISTS (
      SELECT 1
      FROM appointments AS a
      WHERE a.technician_id = t.id
        AND a.status = 'confirmed'
        AND a.start_time_utc < $3
        AND a.end_time_utc > $4
  )
ORDER BY t.id
`

type FindAvailableTechniciansParams struct {
	ServiceTypeID  pgtype.UUID        `json:"service_type_id"`
	DealershipID   pgtype.UUID        `json:"dealership_id"`
	RequestedEnd   pgtype.Timestamptz `json:"requested_end"`
	RequestedStart pgtype.Timestamptz `json:"requested_start"`
}

func (q *Queries) FindAvailableTechnicians(ctx context.Context, arg FindAvailableTechniciansParams) ([]Technician, error) {
	rows, err := q.db.Query(ctx, findAvailableTechnicians,
		arg.ServiceTypeID,
		arg.DealershipID,
		arg.RequestedEnd,
		arg.RequestedStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Technician{}
	for rows.Next() {
		var i Technician
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.Name,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointment = `-- name: GetAppointment :one
SELECT id, customer_id, vehicle_id, dealership_id, technician_id, service_bay_id, service_type_id, start_time_utc, end_time_utc, status, created_at_utc
FROM appointments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAppointment(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VehicleID,
		&i.DealershipID,
		&i.TechnicianID,
		&i.ServiceBayID,
		&i.ServiceTypeID,
		&i.StartTimeUtc,
		&i.EndTimeUtc,
		&i.Status,
		&i.CreatedAtUtc,
	)
	return i, err
}

const listAppointmentsByDealership = `-- name: ListAppointmentsByDealership :many
SELECT id, customer_id, vehicle_id, dealership_id, technician_id, service_bay_id, service_type_id, start_time_utc, end_time_utc, status, created_at_utc
FROM appointments
WHERE dealership_id = $1
  AND start_time_utc < $2
  AND end_time_utc > $3
ORDER BY start_time_utc, id
`

type ListAppointmentsByDealershipParams struct {
	DealershipID pgtype.UUID        `json:"dealership_id"`
	RangeEnd     pgtype.Timestamptz `json:"range_end"`
	RangeStart   pgtype.Timestamptz `json:"range_start"`
}

func (q *Queries) ListAppointmentsByDealership(ctx context.Context, arg ListAppointmentsByDealershipParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByDealership, arg.DealershipID, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.VehicleID,
			&i.DealershipID,
			&i.TechnicianID,
			&i.ServiceBayID,
			&i.ServiceTypeID,
			&i.StartTimeUtc,
			&i.EndTimeUtc,
			&i.Status,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
