// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyRequest = `-- name: CompleteIdempotencyRequest :one
UPDATE idempotency_requests
SET status = 'completed',
    appointment_id = $1,
    response_status = $2,
    response_body = $3
WHERE key = $4
  AND status = 'in_progress'
RETURNING key, request_hash, status, appointment_id, response_status, response_body, created_at_utc, expires_at_utc
`

type CompleteIdempotencyRequestParams struct {
	AppointmentID  pgtype.UUID `json:"appointment_id"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   []byte      `json:"response_body"`
	Key            string      `json:"key"`
}

func (q *Queries) CompleteIdempotencyRequest(ctx context.Context, arg CompleteIdempotencyRequestParams) (IdempotencyRequest, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyRequest,
		arg.AppointmentID,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.Key,
	)
	var i IdempotencyRequest
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.Status,
		&i.AppointmentID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAtUtc,
		&i.ExpiresAtUtc,
	)
	return i, err
}

const createIdempotencyRequest = `-- name: CreateIdempotencyRequest :execrows
INSERT INTO idempotency_requests (
    key,
    request_hash,
    status,
    expires_at_utc
) VALUES (
    $1,
    $2,
    'in_progress',
    $3
)
ON CONFLICT (key) DO NOTHING
`

type CreateIdempotencyRequestParams struct {
	Key          string             `json:"key"`
	RequestHash  string             `json:"request_hash"`
	ExpiresAtUtc pgtype.Timestamptz `json:"expires_at_utc"`
}

func (q *Queries) CreateIdempotencyRequest(ctx context.Context, arg CreateIdempotencyRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, createIdempotencyRequest, arg.Key, arg.RequestHash, arg.ExpiresAtUtc)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyRequests = `-- name: DeleteExpiredIdempotencyRequests :execrows
DELETE FROM idempotency_requests
WHERE expires_at_utc < $1
`

func (q *Queries) DeleteExpiredIdempotencyRequests(ctx context.Context, nowUtc pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyRequests, nowUtc)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyRequest = `-- name: GetIdempotencyRequest :one
SELECT key, request_hash, status, appointment_id, response_status, response_body, created_at_utc, expires_at_utc
FROM idempotency_requests
WHERE key = $1
LIMIT 1
`

func (q *Queries) GetIdempotencyRequest(ctx context.Context, key string) (IdempotencyRequest, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRequest, key)
	var i IdempotencyRequest
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.Status,
		&i.AppointmentID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAtUtc,
		&i.ExpiresAtUtc,
	)
	return i, err
}
