// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID            pgtype.UUID        `json:"id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	VehicleID     pgtype.UUID        `json:"vehicle_id"`
	DealershipID  pgtype.UUID        `json:"dealership_id"`
	TechnicianID  pgtype.UUID        `json:"technician_id"`
	ServiceBayID  pgtype.UUID        `json:"service_bay_id"`
	ServiceTypeID pgtype.UUID        `json:"service_type_id"`
	StartTimeUtc  pgtype.Timestamptz `json:"start_time_utc"`
	EndTimeUtc    pgtype.Timestamptz `json:"end_time_utc"`
	Status        string             `json:"status"`
	CreatedAtUtc  pgtype.Timestamptz `json:"created_at_utc"`
}

type Customer struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	CreatedAtUtc pgtype.Timestamptz `json:"created_at_utc"`
}

type Dealership struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Timezone     string             `json:"timezone"`
	CreatedAtUtc pgtype.Timestamptz `json:"created_at_utc"`
}

type IdempotencyRequest struct {
	Key            string             `json:"key"`
	RequestHash    string             `json:"request_hash"`
	Status         string             `json:"status"`
	AppointmentID  pgtype.UUID        `json:"appointment_id"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAtUtc   pgtype.Timestamptz `json:"created_at_utc"`
	ExpiresAtUtc   pgtype.Timestamptz `json:"expires_at_utc"`
}

type ServiceBay struct {
	ID           pgtype.UUID        `json:"id"`
	DealershipID pgtype.UUID        `json:"dealership_id"`
	Name         string             `json:"name"`
	CreatedAtUtc pgtype.Timestamptz `json:"created_at_utc"`
}

type ServiceBayCapability struct {
	ServiceBayID  pgtype.UUID `json:"service_bay_id"`
	ServiceTypeID pgtype.UUID `json:"service_type_id"`
}

type ServiceType struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	DurationMinutes int32              `json:"duration_minutes"`
	RequiredSkill   string             `json:"required_skill"`
	CreatedAtUtc    pgtype.Timestamptz `json:"created_at_utc"`
}

type Technician struct {
	ID           pgtype.UUID        `json:"id"`
	DealershipID pgtype.UUID        `json:"dealership_id"`
	Name         string             `json:"name"`
	CreatedAtUtc pgtype.Timestamptz `json:"created_at_utc"`
}

type TechnicianSkill struct {
	TechnicianID pgtype.UUID `json:"technician_id"`
	Skill        string      `json:"skill"`
}

type Vehicle struct {
	ID           pgtype.UUID        `json:"id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	Vin          string             `json:"vin"`
	Make         string             `json:"make"`
	Model        string             `json:"model"`
	CreatedAtUtc pgtype.Timestamptz `json:"created_at_utc"`
}
